name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-and-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev

    - name: Check formatting
      run: cargo fmt --all -- --check
      continue-on-error: true

    - name: Test
      run: cargo test --verbose

    - name: Build
      run: cargo build

  build-linux-and-web:

    runs-on: ubuntu-latest
    needs: test-and-build

    steps:

      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev

      - name: Build
        run: cargo build --release --target x86_64-unknown-linux-gnu --verbose

      - name: Build Web
        run: |
          rustup target add wasm32-unknown-unknown
          cargo build --release --target wasm32-unknown-unknown --verbose

  build-windows:

      runs-on: windows-latest
      needs: test-and-build

      steps:

        - uses: actions/checkout@v4

        - name: Build
          run: cargo build --release --target x86_64-pc-windows-msvc --verbose

  build-macos-intel:

    runs-on: macos-13
    needs: test-and-build

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: cargo build --release --target x86_64-apple-darwin --verbose

  build-macos-apple-silicon:

    runs-on: macos-latest
    needs: test-and-build

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: cargo build --release --target aarch64-apple-darwin --verbose

  release:
    needs: [build-linux-and-web, build-windows, build-macos-intel, build-macos-apple-silicon]
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Delete old release
        id: delete_release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh auth status
          gh release delete latest || true